services:
  app:
    # The container name must be "application-server"
    container_name: "application-server"
    # This can be either a pre-existing image or built from a Dockerfile
    image: "${templateOption:image}"
    # build:
    #   context: .
    environment:
      NOTEBOOK_ARGS: "--ServerApp.token='' --ServerApp.password='' --ServerApp.root_dir=${templateOption:homeDir}/work --ServerApp.allow_origin='*'"
    restart: always
    volumes:
      - .:/workspace:cached
      - work:${templateOption:homeDir}/work
    # The port specified here will be forwarded and accessible from the
    # Workbench UI.
    ports:
      - ${templateOption:port}:${templateOption:port}
    # The service must be connected to the "app-network" Docker network
    networks:
      - app-network
    # SYS_ADMIN and fuse are required to mount workspace resources into the
    # container.
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined

volumes:
  work:

networks:
  # The Docker network must be named "app-network". This is an external network
  # that is created outside of this docker-compose file.
  app-network:
    external: true
